# Generated by Django 4.2.1 on 2023-05-28 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_creating',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 14, 41, 18, 400647), verbose_name='Дата создания'),
        ),
    ]
