# Generated by Django 4.2.1 on 2023-05-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category_alter_product_data_creating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_creating',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_updating',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
