# Generated by Django 4.2.1 on 2023-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_data_creating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('preview', models.ImageField(default='preview/default.JPG', upload_to='blog/preview')),
                ('data_creating', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(default='preview/default.JPG', upload_to='preview'),
        ),
    ]
